{% set name = "Mathics3" %}
{% set version = "9.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 8b49c156b012dd8ac9ebb08963208a7de3651cd1eb048ec60a4e1f9be586e703

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mathics = mathics.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
    - setuptools >=70.0.0
  run:
    - cython >=0.15.1
    - Mathics-Scanner >=1.4.1
    - mpmath >=1.2.0
    - numpy
    - palettable
    - stopit
    - pillow >=9.2
    - pint
    - python
    - python-dateutil
    - pywin32-on-windows
    - Pympler
    - requests
    - scipy
    - setuptools >=70.0.0
    - packaging
    - sympy >=1.13,<1.14
test:
  imports:
    - mathics
    - mathics.algorithm
  commands:
    - pip check
    - mathics --help
  requires:
    - pip

about:
  home: https://mathics.org/
  summary: A general-purpose computer algebra system.
  license: GPL-2.0-or-later
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - wolfv
    - rocky
    - mmatera
    - GarkGarcia
