{% set name = "mathics3" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mathics3-{{ version }}.tar.gz
  sha256: ee0b44add808683d84200bc09d8091fa9652fe4ff0cbb3d690b0ff52651a691d

build:
  number: 1
  skip: true  # [py<38]
  entry_points:
    - mathics = mathics.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}  
  host:
    - python
    - setuptools >=70.0.0
    - cython >=0.15.1
    - mathics-scanner >=1.4.0
    - packaging
    - pip
  run:
    - python
    {% if pkg_type == 'pywin32' %}
    - pywin32
    {% else %}
    - __unix
    {% endif %}    
    - mathics-scanner >=1.4.1
    - mpmath >=1.2.0
    - numpy <1.27
    - palettable
    - stopit  # [not emscripten]
    - pillow >=9.2
    - pint
    - python-dateutil
    - pympler
    - requests
    - scipy
    - setuptools
    - sympy >=1.13,<1.14

test:
  imports:
    - mathics
    - mathics.algorithm    
  commands:
    - pip check
    - mathics --help
  requires:
    - pip

about:
  home: https://mathics.org/
  summary: A general-purpose computer algebra system.
  license: GPL-2.0-or-later  
  license_file:
    - COPYING.txt
    - mathics/data/ExampleData/copyright.csv

extra:
  recipe-maintainers:
    - wolfv
    - rocky
    - mmatera
    - GarkGarcia
