{% set name = "Mathics3" %}
{% set version = "7.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Mathics3-{{ version }}.tar.gz
  sha256: 2a4b59f824a1ebdc2390783839b4aa2920db2dc4cebc3286d2b0bb1543cc7fd2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mathics = mathics.main:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - cython >=0.15.1
    - Mathics-Scanner >=1.3.0
    - mpmath >=1.2.0
    - numpy <1.27
    - palettable
    - stopit
    - pillow >=9.2
    - pint
    - python
    - python-dateutil
    - Pympler
    - requests
    - scipy
    - setuptools >70.0.0
    - packaging
    - sympy >=1.13,<1.14
test:
  imports:
    - mathics
    - mathics.algorithm
  commands:
    - pip check
    - mathics --help
  requires:
    - pip

about:
  home: https://mathics.org/
  summary: A general-purpose computer algebra system.
  license: GPL-2.0-or-later
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - wolfv
    - rocky
    - mmatera
    - GarkGarcia
