{% set name = "mathics3" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Mathics3-{{ version }}.tar.gz
  sha256: 07a1f67e8a856f4b2a28ce724ec51a6e1ab074d4f1a6e024a7bf5d1482c87bb7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mathics = mathics.main:main
    - mathicsserver = mathics.server:main
    - mathicsscript = mathics.script:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - cython >=0.15.1
    - django >=3.0,<3.2
    - llvmlite
    - mpmath >=1.1.0
    - numpy
    - palettable
    - pint
    - python
    - python-dateutil
    - requests
    - sympy >=1.7,<1.8
    - scikit-image
    - wordcloud
test:
  imports:
    - mathics
    - mathics.algorithm
  commands:
    - pip check
    - mathics --help
    - mathicsserver --help
    - mathicsscript --help  # [not win]
  requires:
    - pip

about:
  home: https://mathics.org/
  summary: A general-purpose computer algebra system.
  license: GPL-3.0
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - wolfv
    - rocky
    - mmatera
    - GarkGarcia
